spring.application.name=inventory-service
server.port=${PORT:8081}
#spring.datasource.url=jdbc:mysql://localhost:3306/crate_management
#spring.datasource.username=root
#spring.datasource.password=Bismillah@123
spring.datasource.url=jdbc:postgresql://ep-lucky-king-amdxp4cd.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ratVW9yc1Nsp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

